// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tunnelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TunnelClient is the client API for Tunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelClient interface {
	NewStream(ctx context.Context, opts ...grpc.CallOption) (Tunnel_NewStreamClient, error)
}

type tunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelClient(cc grpc.ClientConnInterface) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) NewStream(ctx context.Context, opts ...grpc.CallOption) (Tunnel_NewStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tunnel_serviceDesc.Streams[0], "/Tunnel/NewStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelNewStreamClient{stream}
	return x, nil
}

type Tunnel_NewStreamClient interface {
	Send(*Up) error
	Recv() (*Down, error)
	grpc.ClientStream
}

type tunnelNewStreamClient struct {
	grpc.ClientStream
}

func (x *tunnelNewStreamClient) Send(m *Up) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelNewStreamClient) Recv() (*Down, error) {
	m := new(Down)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServer is the server API for Tunnel service.
// All implementations must embed UnimplementedTunnelServer
// for forward compatibility
type TunnelServer interface {
	NewStream(Tunnel_NewStreamServer) error
	mustEmbedUnimplementedTunnelServer()
}

// UnimplementedTunnelServer must be embedded to have forward compatible implementations.
type UnimplementedTunnelServer struct {
}

func (UnimplementedTunnelServer) NewStream(Tunnel_NewStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method NewStream not implemented")
}
func (UnimplementedTunnelServer) mustEmbedUnimplementedTunnelServer() {}

// UnsafeTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServer will
// result in compilation errors.
type UnsafeTunnelServer interface {
	mustEmbedUnimplementedTunnelServer()
}

func RegisterTunnelServer(s grpc.ServiceRegistrar, srv TunnelServer) {
	s.RegisterService(&_Tunnel_serviceDesc, srv)
}

func _Tunnel_NewStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).NewStream(&tunnelNewStreamServer{stream})
}

type Tunnel_NewStreamServer interface {
	Send(*Down) error
	Recv() (*Up, error)
	grpc.ServerStream
}

type tunnelNewStreamServer struct {
	grpc.ServerStream
}

func (x *tunnelNewStreamServer) Send(m *Down) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelNewStreamServer) Recv() (*Up, error) {
	m := new(Up)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Tunnel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewStream",
			Handler:       _Tunnel_NewStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/tunnel/tunnelpb/tunnel.proto",
}
