# syntax = docker/dockerfile:1-experimental

ARG GO_VERSION=1.18

FROM golang:${GO_VERSION}-bullseye AS builder

WORKDIR /src
ENV CGO_ENABLED=0
COPY go.* .
RUN --mount=type=cache,target=/go/pkg    go mod download -x

COPY ./ ./
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    go build  -o /udig ./cmd/udigd

# is this still necessary?
RUN apt-get update && apt-get install --yes libcap2-bin
RUN setcap 'cap_net_bind_service+eip' /udig

# distroless with busybox
FROM gcr.io/distroless/base@sha256:9e6e03068e43358fd02a9bb967f5735587673c0ede0267b4d0d1cd0e0142bc08

COPY --from=builder /udig /udig

COPY --from=builder /sbin/getcap /sbin
COPY --from=builder /sbin/setcap /sbin
COPY --from=builder /lib/*-linux-gnu/libcap.so.2 /lib

RUN ["/sbin/setcap", "cap_net_bind_service=+ep", "/udig"]

EXPOSE 8053/udp

USER 1000:1000

ENTRYPOINT ["/udig"]
