// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pkg/uplink/uplinkpb/uplink.proto

package uplinkpb

import (
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RegisterTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *RegisterTrigger) Reset() {
	*x = RegisterTrigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrigger) ProtoMessage() {}

func (x *RegisterTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrigger.ProtoReflect.Descriptor instead.
func (*RegisterTrigger) Descriptor() ([]byte, []int) {
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTrigger) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The public key used to sign the nonce.
	//
	// existing encoding standards like pkcs#12 and pem are slow to gain support for
	// new ciphers; for now we'll just encode the type of the public key in the proto
	// schema and deal with cipher evolution by evolving the proto.
	Ed25519PublicKey []byte `protobuf:"bytes,1,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"`
	// The signature of the nonce.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// request that the tunnel broker has at least one of these ports open.
	// if the broker doesn't have (or allow) some of these ports, they won't be
	// present in the "ingress" repeated field of the subsequent Setup message.
	// The client might treat the lack of a requested port as a fatal error.
	Ports []int32 `protobuf:"varint,3,rep,packed,name=ports,proto3" json:"ports,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *RegisterRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RegisterRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type SetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Setup:
	//	*SetupRequest_Ingress_
	//	*SetupRequest_Redirect_
	//	*SetupRequest_Error
	Setup isSetupRequest_Setup `protobuf_oneof:"setup"`
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP(), []int{2}
}

func (m *SetupRequest) GetSetup() isSetupRequest_Setup {
	if m != nil {
		return m.Setup
	}
	return nil
}

func (x *SetupRequest) GetIngress() *SetupRequest_Ingress {
	if x, ok := x.GetSetup().(*SetupRequest_Ingress_); ok {
		return x.Ingress
	}
	return nil
}

func (x *SetupRequest) GetRedirect() *SetupRequest_Redirect {
	if x, ok := x.GetSetup().(*SetupRequest_Redirect_); ok {
		return x.Redirect
	}
	return nil
}

func (x *SetupRequest) GetError() *status.Status {
	if x, ok := x.GetSetup().(*SetupRequest_Error); ok {
		return x.Error
	}
	return nil
}

type isSetupRequest_Setup interface {
	isSetupRequest_Setup()
}

type SetupRequest_Ingress_ struct {
	Ingress *SetupRequest_Ingress `protobuf:"bytes,1,opt,name=ingress,proto3,oneof"`
}

type SetupRequest_Redirect_ struct {
	Redirect *SetupRequest_Redirect `protobuf:"bytes,2,opt,name=redirect,proto3,oneof"`
}

type SetupRequest_Error struct {
	// in case of any error setting up the tunnel, the server will send the
	// status here (because it cannot respond with an error to the RegisterResponse
	// response, because it's already a response).
	//
	// TODO(mkm): find a way to make go mod work with protobuf source imports.
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*SetupRequest_Ingress_) isSetupRequest_Setup() {}

func (*SetupRequest_Redirect_) isSetupRequest_Setup() {}

func (*SetupRequest_Error) isSetupRequest_Setup() {}

type SetupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP(), []int{3}
}

type SetupRequest_Ingress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hostname:port pairs where the tunnel will be accessible to external clients.
	Ingress []string `protobuf:"bytes,1,rep,name=ingress,proto3" json:"ingress,omitempty"`
}

func (x *SetupRequest_Ingress) Reset() {
	*x = SetupRequest_Ingress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupRequest_Ingress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest_Ingress) ProtoMessage() {}

func (x *SetupRequest_Ingress) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest_Ingress.ProtoReflect.Descriptor instead.
func (*SetupRequest_Ingress) Descriptor() ([]byte, []int) {
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SetupRequest_Ingress) GetIngress() []string {
	if x != nil {
		return x.Ingress
	}
	return nil
}

type SetupRequest_Redirect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the tunnel request is accepted by this broker instance is not the right
	// endpoint the setup a durable tunnel session.
	// The client should try again to setup the tunnel by contact to one or more of
	// these host:port pairs.
	RedirectTo []string `protobuf:"bytes,2,rep,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
}

func (x *SetupRequest_Redirect) Reset() {
	*x = SetupRequest_Redirect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupRequest_Redirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest_Redirect) ProtoMessage() {}

func (x *SetupRequest_Redirect) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest_Redirect.ProtoReflect.Descriptor instead.
func (*SetupRequest_Redirect) Descriptor() ([]byte, []int) {
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP(), []int{2, 1}
}

func (x *SetupRequest_Redirect) GetRedirectTo() []string {
	if x != nil {
		return x.RedirectTo
	}
	return nil
}

var File_pkg_uplink_uplinkpb_uplink_proto protoreflect.FileDescriptor

var file_pkg_uplink_uplinkpb_uplink_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x75, 0x70, 0x6c,
	0x69, 0x6e, 0x6b, 0x70, 0x62, 0x2f, 0x75, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0f, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x22, 0x73, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x64, 0x32, 0x35, 0x35,
	0x31, 0x39, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0xfe, 0x01, 0x0a, 0x0c, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x34, 0x0a,
	0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a,
	0x23, 0x0a, 0x07, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x1a, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x54,
	0x6f, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x60, 0x0a, 0x06, 0x55,
	0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x2e, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x10, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x0d,
	0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x74, 0x6e,
	0x61, 0x6d, 0x69, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x75, 0x64, 0x69, 0x67, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x75, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x75, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_uplink_uplinkpb_uplink_proto_rawDescOnce sync.Once
	file_pkg_uplink_uplinkpb_uplink_proto_rawDescData = file_pkg_uplink_uplinkpb_uplink_proto_rawDesc
)

func file_pkg_uplink_uplinkpb_uplink_proto_rawDescGZIP() []byte {
	file_pkg_uplink_uplinkpb_uplink_proto_rawDescOnce.Do(func() {
		file_pkg_uplink_uplinkpb_uplink_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_uplink_uplinkpb_uplink_proto_rawDescData)
	})
	return file_pkg_uplink_uplinkpb_uplink_proto_rawDescData
}

var file_pkg_uplink_uplinkpb_uplink_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_uplink_uplinkpb_uplink_proto_goTypes = []interface{}{
	(*RegisterTrigger)(nil),       // 0: RegisterTrigger
	(*RegisterRequest)(nil),       // 1: RegisterRequest
	(*SetupRequest)(nil),          // 2: SetupRequest
	(*SetupResponse)(nil),         // 3: SetupResponse
	(*SetupRequest_Ingress)(nil),  // 4: SetupRequest.Ingress
	(*SetupRequest_Redirect)(nil), // 5: SetupRequest.Redirect
	(*status.Status)(nil),         // 6: google.rpc.Status
}
var file_pkg_uplink_uplinkpb_uplink_proto_depIdxs = []int32{
	4, // 0: SetupRequest.ingress:type_name -> SetupRequest.Ingress
	5, // 1: SetupRequest.redirect:type_name -> SetupRequest.Redirect
	6, // 2: SetupRequest.error:type_name -> google.rpc.Status
	0, // 3: Uplink.Register:input_type -> RegisterTrigger
	2, // 4: Uplink.Setup:input_type -> SetupRequest
	1, // 5: Uplink.Register:output_type -> RegisterRequest
	3, // 6: Uplink.Setup:output_type -> SetupResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_uplink_uplinkpb_uplink_proto_init() }
func file_pkg_uplink_uplinkpb_uplink_proto_init() {
	if File_pkg_uplink_uplinkpb_uplink_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTrigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupRequest_Ingress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupRequest_Redirect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_uplink_uplinkpb_uplink_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SetupRequest_Ingress_)(nil),
		(*SetupRequest_Redirect_)(nil),
		(*SetupRequest_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_uplink_uplinkpb_uplink_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_uplink_uplinkpb_uplink_proto_goTypes,
		DependencyIndexes: file_pkg_uplink_uplinkpb_uplink_proto_depIdxs,
		MessageInfos:      file_pkg_uplink_uplinkpb_uplink_proto_msgTypes,
	}.Build()
	File_pkg_uplink_uplinkpb_uplink_proto = out.File
	file_pkg_uplink_uplinkpb_uplink_proto_rawDesc = nil
	file_pkg_uplink_uplinkpb_uplink_proto_goTypes = nil
	file_pkg_uplink_uplinkpb_uplink_proto_depIdxs = nil
}
