// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/uplink/uplinkpb/uplink.proto

package uplinkpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("pkg/uplink/uplinkpb/uplink.proto", fileDescriptor_4b16aec953f09314) }

var fileDescriptor_4b16aec953f09314 = []byte{
	// 58 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xc8, 0x4e, 0xd7,
	0x2f, 0x2d, 0xc8, 0xc9, 0xcc, 0xcb, 0x86, 0x52, 0x05, 0x49, 0x50, 0x86, 0x5e, 0x41, 0x51, 0x7e,
	0x49, 0xbe, 0x13, 0x57, 0x14, 0x07, 0x4c, 0x22, 0x89, 0x0d, 0x2c, 0x64, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x55, 0x59, 0x61, 0xf8, 0x36, 0x00, 0x00, 0x00,
}
